#!/bin/bash
#SBATCH --image=docker:oushujun/edta:2.0.0
#SBATCH --qos=jgi_exvivo
#SBATCH --time=168:00:00
#SBATCH --nodes=1
#SBATCH --account=plant
#SBATCH --job-name=EDTA_Hvul
#SBATCH --output=EDTA_Hvul-%l.out
#SBATCH --error=EDTA_Hvul-%l.err

cd /global/cfs/cdirs/plantbox/llei/cscratch/CSP_Dave/TE_anno/Hvul

/usr/bin/time -v shifter -i oushujun/edta:2.0.0 EDTA.pl --genome /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/HvulgareMorexV3/assembly/HvulgareMorex_702_V3.fa --cds /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/HvulgareMorexV3/annotation/HvulgareMorex_702_V3.cds_primaryTranscriptOnly.fa --overwrite 0 --sensitive 1 --anno 1 --evaluate 1 --threads 20
