#!/bin/bash
#SBATCH --qos=genepool
#SBATCH --time=5:00:00
#SBATCH --nodes=1
#SBATCH --account=plant
#SBATCH --job-name=MSA_muscle
#SBATCH --output=%x%j.out
#SBATCH --error=%x%j.err

cd /global/cfs/cdirs/plantbox/llei/bscratch/llei2019/software

FASTAFILES=($(cat /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/orth_tree/fasta_8525_file.list))
CURRENT_FASTAFILES=${FASTAFILES[${SLURM_ARRAY_TASK_ID}]}
GENES=($(awk -F"/" '{print $NF}' /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/orth_tree/fasta_8525_file.list|awk -F ".fasta" '{print $1}'))
CURRENT_GENES=${GENES[${SLURM_ARRAY_TASK_ID}]}

./muscle3.8.31_i86linux64 -in ${CURRENT_FASTAFILES}  -out /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/orth_tree/MSA/${CURRENT_GENES}.MSA.fasta

