#!/bin/bash
#SBATCH --image=docker:oushujun/edta:2.0.0
#SBATCH --qos=jgi_exvivo
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --account=plant
#SBATCH --job-name=EDTA_Bhyb
#SBATCH --output=EDTA_Bhyb-%l.out
#SBATCH --error=EDTA_Bhyb-%l.err

cd /global/cfs/cdirs/plantbox/llei/cscratch/CSP_Dave/TE_anno/Bhyb

/usr/bin/time -v shifter -i oushujun/edta:2.0.0 EDTA.pl --genome /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/Bhybridum/assembly/Bhybridum_463_v1.0.fa --cds /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/Bhybridum/annotation/Bhybridum_463_v1.1.cds_primaryTranscriptOnly_cutName.fa --overwrite 0 --sensitive 1 --anno 1 --evaluate 1 --threads 20