#!/bin/bash
#SBATCH --image=docker:oushujun/edta:2.0.0
#SBATCH --qos=jgi_exvivo
#SBATCH --time=168:00:00
#SBATCH --nodes=1
#SBATCH --account=plant
#SBATCH --job-name=EDTA_Sbic
#SBATCH --output=%EDTA_Sbic%l.out
#SBATCH --error=%EDTA_Sbic%l.err

cd /global/cfs/cdirs/plantbox/llei/cscratch/CSP_Dave/TE_anno/Sbic

/usr/bin/time -v shifter -i oushujun/edta:2.0.0 EDTA.pl --genome /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/Sbicolor/assembly/Sbicolor_454_v3.0.1.fa --cds /global/u2/l/llei2019/plantbox/cscratch/CSP_Dave/Genome_assembly/Sbicolor/annotation/Sbicolor_454_v3.1.1.cds_primaryTranscriptOnly.fa --overwrite 0 --sensitive 1 --anno 1 --evaluate 1 --threads 20
